services:
  next:
    image: node:alpine
    build: ./

    ports:
      - 3001:3000

    develop:
      watch:
        - action: sync
          path: ./
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    
    volumes:
      - /app

volumes:
  next:
